### ISSUE TITLE
Guidance: pattern and samples for 1es template adoption (official and unofficial templates)

### ISSUE THREAD

**Issue by chcosta** [dotnet/dnceng#2159]
This issue tracks this bullet-point from https://github.com/dotnet/dnceng/issues/2148

> There is guidance, a pattern and samples for authoring templates that can be shared between official and unofficial, and don't run excessive SDL scans.

**Comment by chcosta** [comment]
We can conditionalize Microbuild / 1ES template usage via variables.  ie, we can propose one of the following patterns.

azure-pipelines.yml
``` yaml
variables:
- ${{ if and(ne(variables['System.TeamProject'], 'public'), in(variables['Build.Reason'], 'Schedule')) }}:
  - name: oneespttemplate
    value: azure-pipelines/MicroBuild.1ES.Official.yml@MicroBuildTemplate
- ${{ if and(ne(variables['System.TeamProject'], 'public'), notIn(variables['Build.Reason'], 'Schedule')) }}:
  - name: oneespttemplate
    value: azure-pipelines/MicroBuild.1ES.Unofficial.yml@MicroBuildTemplate
resources:
  repositories:
  - repository: MicroBuildTemplate
    type: git
    name: 1ESPipelineTemplates/MicroBuildTemplate
    ref: refs/tags/release
extends:
  template: ${{ variables['oneespttemplate'] }}
```

or

variables.yml
``` yaml
variables:
- ${{ if and(ne(variables['System.TeamProject'], 'public'), in(variables['Build.Reason'], 'Schedule')) }}:
  - name: oneespttemplate
    value: azure-pipelines/MicroBuild.1ES.Official.yml@MicroBuildTemplate
- ${{ if and(ne(variables['System.TeamProject'], 'public'), notIn(variables['Build.Reason'], 'Schedule')) }}:
  - name: oneespttemplate
    value: azure-pipelines/MicroBuild.1ES.Unofficial.yml@MicroBuildTemplate
```

azure-pipelines.yml
``` yaml
variables:
- template: variables.yml
resources:
  repositories:
  - repository: MicroBuildTemplate
    type: git
    name: 1ESPipelineTemplates/MicroBuildTemplate
    ref: refs/tags/release
extends:
  template: ${{ variables['oneespttemplate'] }}
```

I don't know that we should provide a "variables.yml" template via Arcade unless we find there to be a consistent pattern for the conditions.  It feels like teams will have slightly different needs and need to control the conditions themselves.

FYI @riarenas
