### ISSUE TITLE
Use YAML templates for `FORCE_QUEUE` detection

### ISSUE THREAD

**Issue by premun** [dotnet/dnceng#267]
There is a lot of repetition in the `dotnet-helix-machines` pipeline YAML around detection of `FORCE_QUEUE` which can be easily de-duplicated into a YAML template.

Specifically this bit:
```yaml
- ${{ if eq(variables['Build.Reason'], 'PullRequest') }}:
    - powershell: eng/get-forcedbranches.ps1 -SourceBranch $(System.PullRequest.SourceBranch) -TargetBranch $(System.PullRequest.TargetBranch)
      displayName: Commit FORCE_QUEUE Example -> ForceQueues
```

Logged this issue as an outcome of https://dev.azure.com/dnceng/internal/_git/dotnet-helix-machines/pullrequest/32013

### Release Note Category
- [ ] Feature changes/additions 
- [ ] Bug fixes
- [x] Internal Infrastructure Improvements
### Release Note Description

Deduplicate YAML steps around `FORCE_QUEUE` logic
