### ISSUE TITLE
New Helix Queue for Tethered AppleTVs

### ISSUE THREAD

**Issue by ilyas1974** [dotnet/dnceng#2768]
Per request from the product team, they would like to move the systems currently running macOS 11 to a new queue that is running the latest Apple OS. 

Please create a new queue called macos.arm64.appletv.open (the existing osx.14.arm64.open and osx.1100.arm64.appletv.open queues can be used as "baselines" for this new queue). 
Once the queue has been created, we will need to reach out to DDFUN to update the systems to the latest Apple OS and move them to this new queue. 

### Release Note Category
- [ ] Feature changes/additions 
- [ ] Bug fixes
- [ ] Internal Infrastructure Improvements
### Release Note Description
Create Tethered AppleTV Helix queue

**Comment by chcosta** [comment]
ack

**Comment by chcosta** [comment]
osx.14.arm64.open
```yaml
- &OSX-14-00-ARM64
  <<: *Base
  Name: OSX.14.Arm64.Open
  OperatingSystemId: Apple-macOS-14.00-ARM64
  # No real EstimatedRemovalDate for this queue
  UpdateRequiredDate: 2025-01-01
  EstimatedRemovalDate: 2025-01-01
  Architecture: ARM64
  Public: true
  PreInstalledImage:
    System: Darwin
    Version: 23.0.0
    Processor: arm64
    Distro: macOS
    DistroVersion: 14.00
  Artifacts:
  - Name: macos-xcode
    Parameters:
      version: 15.0.1
    UpdateDate: 2024-06-30
  - *OSXArtifacts
```

osx.1100.arm64.appletv.open
```yaml
- &OSX-11-00-ARM64-AppleTV-Open
  <<: *OSX-11-00-M1
  Name: OSX.1100.Arm64.AppleTV.Open
  Public: true
  Artifacts:
  - Name: macos-rosetta
  - Name: macos-xcode
    Parameters:
      version: 13.0
    UpdateDate: 2024-06-30
  - *OSXArtifacts
  - Name: macos-signing-certs
    Parameters:
      user: helix-runner
  TetheredDevices:
  - OperatingSystemId: Apple-tvOS-15.0-ARM64
    DeviceModel: Apple_TV
```

Based on our conversation, what needs to be done is to use osx.14.arm64.open for OS info and osx.1100.arm64.appletv.open for the rest.  So, something like...

macos.arm64.appletv.open
```yaml
&MacOS-ARM64-AppleTV-Open
  <<: *Base
  Name: MacOS.Arm64.AppleTV.Open
  OperatingSystemId: Apple-macOS-14.00-ARM64
  # No real EstimatedRemovalDate for this queue
  UpdateRequiredDate: 2025-01-01
  EstimatedRemovalDate: 2025-01-01
  Architecture: ARM64
  Public: true
  PreInstalledImage:
    System: Darwin
    Version: 23.0.0
    Processor: arm64
    Distro: macOS
    DistroVersion: 14.00
  Artifacts:
  - Name: macos-rosetta
  - Name: macos-xcode
    Parameters:
      version: 13.0
    UpdateDate: 2024-06-30
  - *OSXArtifacts
  - Name: macos-signing-certs
    Parameters:
      user: helix-runner
  TetheredDevices:
  - OperatingSystemId: Apple-tvOS-15.0-ARM64
    DeviceModel: Apple_TV
```

@ilyas1974 thoughts?
