### ISSUE TITLE
Secret-manager maintaining encryption keys

### ISSUE THREAD

**Issue by MilenaHristova** [dotnet/dnceng#664]
In secrets manifest files there can be a section for `keys` as well as secrets  - from the [documentation](https://github.com/dotnet/dnceng/tree/main/src/SecretManager/Microsoft.DncEng.SecretManager#manifest-files):
```
# encryption keys that are needed in the vault, these keys will be created if they don't exist.
keys:
  data-protection-encryption-key:
    type: RSA    
    size: 2048
```
There are 2 of those - for `maestroint` and `maestroprod` and they expired without us knowing about it: [Teams conversation](https://teams.microsoft.com/l/message/19:276707cdcf5d431caaa8792b29bd832d@thread.skype/1692386268810?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=147df318-61de-4f04-8f7b-ecd328c256bb&parentMessageId=1692386268810&teamName=.NET%20Eng%20Services&channelName=FR%20Internal&createdTime=1692386268810)  

We should probably think of a way to handle those - either extending `secret-manager` functionality to rotate them or adding them as text-type secrets to the manifest so we'll get a notification when they expire 

### Release Note Category
- [ ] Feature changes/additions 
- [ ] Bug fixes
- [ ] Internal Infrastructure Improvements
### Release Note Description
